name: Update FBS

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: |
          git submodule update --remote
          git commit -m "chore: bump fbs version"
          git push
