name: Update FBS

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: |
          git submodule update --init --remote
          git config user.name ${{ github.actor }}
          git config user.email "<${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>"
          git add .
          git commit -m "chore: bump fbs version"
          git push
